logging:
  config: classpath:logConfig/logback-prod.xml

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 65535 # url最大限制
    session:
      timeout: 3600 # session会话超时时间，单位为秒

spring:
  profiles:
    include: mapper,valid #引入 mapper valid 配置

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false

  http:
    converters:
      preferred-json-mapper: fastjson

http:
  encoding:
    charset:  UTF-8 #编码设置
    enabled:  true
    force:  true
  mappers:
    json-pretty-print:  true
  converters:
    preferred-json-mapper: fastjson
  multipart:
    maxFileSize: 10Mb
    maxRequestSize: 100Mb